# Generated by Django 6.0.2 on 2026-02-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=20)),
                ('doctor', models.CharField(max_length=50)),
                ('diagnosis', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
